<a href="https://colab.research.google.com/github/22tanyabansal/Data-Science-ML/blob/main/Numpy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([1,5,6,7,8],dtype='f')
b= np.array((4,7,8,9))
print(a)
print(b)
type(a)
type(b)
a.dtype

[1. 5. 6. 7. 8.]
[4 7 8 9]


dtype('float32')

In [ ]:
import numpy as np
a = np.array([[1,5,6],[7,8,9]])
a.ndim
a[0,1]
a[0,0]

1

In [ ]:
import numpy as np
b = np.array([[[1,5,6],[3,6,3],[2,3,6]],[[7,9,6],[0,8,2],[4,3,2]]])
b.ndim
b[0,1,2]
b[1,0,2]
print(b.shape[0],b.shape[1],b.shape[2])

2 3 3


In [ ]:
import numpy as np
a = np.arange(2,100,4)
print(a)

[ 2  6 10 14 18 22 26 30 34 38 42 46 50 54 58 62 66 70 74 78 82 86 90 94
 98]


In [ ]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
a = np.random.rand(2,3,4,2)
print(a)

[[[[0.48715198 0.30412995]
   [0.03449829 0.70654709]
   [0.50457442 0.71408815]
   [0.56465671 0.37803768]]

  [[0.09317225 0.57847356]
   [0.85736511 0.71102397]
   [0.78619474 0.55739448]
   [0.51113934 0.77456074]]

  [[0.36719594 0.83606832]
   [0.31677094 0.89675408]
   [0.43988221 0.19007541]
   [0.63627119 0.4077778 ]]]


 [[[0.424556   0.2145809 ]
   [0.40383743 0.14448375]
   [0.80699357 0.11330028]
   [0.4115204  0.39356543]]

  [[0.94227557 0.39222992]
   [0.19031212 0.87731982]
   [0.00122783 0.90000128]
   [0.68733457 0.29879979]]

  [[0.5809751  0.22660169]
   [0.94439329 0.97311433]
   [0.13883878 0.49143112]
   [0.31810049 0.02248593]]]]


In [ ]:
b = np.arange(100).reshape(4,25)
print(b)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
  74]
 [75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
  99]]


In [ ]:
A = np.arange(100)
print(A)
B = A[3:10]
print(B)
B[0]=-1200
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[3 4 5 6 7 8 9]
[    0     1     2 -1200     4     5     6     7     8     9    10    11
    12    13    14    15    16    17    18    19    20    21    22    23
    24    25    26    27    28    29    30    31    32    33    34    35
    36    37    38    39    40    41    42    43    44    45    46    47
    48    49    50    51    52    53    54    55    56    57    58    59
    60    61    62    63    64    65    66    67    68    69    70    71
    72    73    74    75    76    77    78    79    80    81    82    83
    84    85    86    87    88    89    90    91    92    93    94    95
    96    97    98    99]


In [ ]:
idx = np.argwhere(A==-1200)[0][0]
print(idx)

3


In [ ]:
A = np.arange(100)
print(A)
B = A[[3,5,7]]
print(B)
B[0]=-4
print(B)
print(A)
B = A[A<40]
print(B)
B = A[(A<40) & (A>30)]
print(B)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[3 5 7]
[-4  5  7]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[31 32 33 34 35 36 37 38 39]


In [ ]:
A = np.round(10*np.random.rand(2,3))
print(A)
A = A+3
print(A)

[[5. 8. 7.]
 [3. 7. 7.]]
[[ 8. 11. 10.]
 [ 6. 10. 10.]]


In [ ]:
B = np.round(10*np.random.rand(2,3))
print(B)
C = np.hstack((A,B))
print(C)
D =  np.vstack((A,B))
print(D)

[[ 9.  2.  4.]
 [ 1. 10.  4.]]
[[ 8. 11. 10.  9.  2.  4.]
 [ 6. 10. 10.  1. 10.  4.]]
[[ 8. 11. 10.]
 [ 6. 10. 10.]
 [ 9.  2.  4.]
 [ 1. 10.  4.]]


In [ ]:
A = np.random.permutation(np.arange(10))
print(A)
A.sort()
print(A)

[8 9 4 5 7 3 1 2 6 0]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
B = np.random.rand(100000)
%timeit sum(B)
%timeit np.sum(B)

6.76 ms ± 51.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
28.2 µs ± 304 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
def mysum(G):
  s=0
  for x in G:
    s+=x
    return s
%timeit mysum(B)

289 ns ± 4.49 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
import pandas as pd
A = pd.Series([2,5,7,8],index=['a','b','c','d'])
print(A)
A.index
A['b']
A['a':'b']

a    2
b    5
c    7
d    8
dtype: int64


a    2
b    5
dtype: int64

In [ ]:
grades_dict = {'A':4,'B':3.5,'C':4,'D':2}
grades = pd.Series(grades_dict)
print(grades)
grades.values

A    4.0
B    3.5
C    4.0
D    2.0
dtype: float64


array([4. , 3.5, 4. , 2. ])

In [ ]:
marks_dict = {'A':45,'B':34,'C':67,'D':90}
marks = pd.Series(marks_dict)
print(marks)

A    45
B    34
C    67
D    90
dtype: int64


In [ ]:
D = pd.DataFrame({'Marks':marks,'Grades':grades})
print(D)

   Marks  Grades
A     45     4.0
B     34     3.5
C     67     4.0
D     90     2.0


In [ ]:
D.values
D.values[2,0]
D.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [ ]:
G = D[D['Marks']>70]
print(G)

   Marks  Grades  Percentage
D     90     2.0         0.9


In [95]:
D['Percentage']= D['Marks']/100
print(D)

   Marks  Grades  Percentage
A     45     4.0        0.45
B     34     3.5        0.34
C     67     4.0        0.67
D     90     2.0        0.90


In [94]:
D.iloc[::-1,:]

Marks  Grades  Percentage
D     90     2.0        0.90
C     67     4.0        0.67
B     34     3.5        0.34
A     45     4.0        0.45

In [76]:
A = pd.DataFrame([{'a':1,'b':-3},{'b':5,'c':8}])
print(A)

     a  b    c
0  1.0 -3  NaN
1  NaN  5  8.0


In [79]:
A.fillna(1)

a  b    c
0  1.0 -3  1.0
1  1.0  5  8.0

In [80]:
A.dropna

<bound method DataFrame.dropna of      a  b    c
0  1.0 -3  NaN
1  NaN  5  8.0>

In [93]:
A = pd.Series([2,5,6],index=['a','b','c'])
print(A)
A.iloc[1:3]

a    2
b    5
c    6
dtype: int64


b    5
c    6
dtype: int64